Crop Screenshot to fit the Bounds of a WindowEvent (#108
MLDSAI/OpenAdapt pull request #142
Opened 2023-05-12 17:07 UTC by AvidEslami

Solves #84 
Summary: Added screenshot.crop_active_window,
- Crops screenshot._image using the bounds of the window_event input parameter.
- Tested using WindowEvents from Recording:
``` Python
#sample test code used in DemoReplayStrategy
screenshot._image.show()  #image 1
screenshot.crop_active_window(window_event)
screenshot._image.show()  #image 2
```

Test Result:
**Image 1:**
![image](https://github.com/MLDSAI/OpenAdapt/assets/34798076/b41b0074-34b7-48fa-92ec-10ec58bd6e53)
**Image 2:**
![image](https://github.com/MLDSAI/OpenAdapt/assets/34798076/63d2dfe4-2998-4609-8c90-8c24309529c8)

TODO: Find the WindowEvent of a screenshot that was not part of a recording. This might be done through a helper function: screenshot.get_window_event which could be called from within crop_active_window instead of passing the WindowEvent as an input parameter.

2023-05-12 17:59 UTC, abrichr commented
Thanks @AvidEslami ! Can you please also show some usage example, ideally as code, or if not as documentation?

2023-05-23 14:35 UTC, abrichr commented
@AvidEslami any update on this?

2023-05-26 01:23 UTC, AvidEslami commented
> Thanks @AvidEslami ! Can you please also show some usage example, ideally as code, or if not as documentation?

Hi! I created a temporary file to function as a quick test, run the python file as follows:
```Python
python .\openadapt\temp_crop_test.py
```
This test will take a screenshot of your current screen, retrieve the first WindowEvent from your latest recording, and will display the cropped and uncropped versions of that screenshot relative to the bounds of the WindowEvent. 

__Status Summary:__
Currently you can crop the screenshots with reference to a WindowEvent if you have access to one, but finding the WindowEvent for a screenshot isn't the easiest unless it is from a recording. In the [Window state pull request](https://github.com/MLDSAI/OpenAdapt/pull/151/files#:~:text=%22screenshots%22-,action_event,-%3D%20sa.) there are some additions to the screenshot class which could make it easier to find the WindowEvents. I'll look into these new changes to see if improvements/additions could be made.

Let me know if there are any issues or suggestions/improvements to be made!

2023-05-27 05:09 UTC, abrichr commented
Thanks @AvidEslami ! Those changes have been merged to master so you should be good to go 👍

2023-05-31 01:55 UTC, 0dm commented
got it working, looks good 👍

2023-05-31 02:39 UTC, 0dm commented
thought it was working, but looks like it's not cropping properly because it's missing ratios:


solution: pass action_event instead of window_event and use this:
```python
    
    def crop_active_window(self, action_event):
        window_event = action_event.window_event
        
        width_ratio, height_ratio = utils.get_scale_ratios(action_event)
        
        x0 = window_event.left * width_ratio
        y0 = window_event.top * height_ratio
        x1 = x0 + window_event.width * width_ratio
        y1 = y0 + window_event.height * height_ratio
        box = (x0, y0, x1, y1)

        self._image = self._image.crop(box)
  ```
  before:
  ![recording-1-0](https://github.com/MLDSAI/OpenAdapt/assets/57018940/2e0d98b5-7e8a-4a86-8151-f634a8377bc6)

  after:
  ![recording-1-0](https://github.com/MLDSAI/OpenAdapt/assets/57018940/22403906-f19c-4e9f-9b7c-7b0222e9e450)

2023-05-31 02:44 UTC, 0dm requested changes

2023-05-31 02:44 UTC, 0dm commented on openadapt/models.py
> +        self._image = self._image.crop(box)
```suggestion
    def crop_active_window(self, action_event):
        window_event = action_event.window_event
        
        width_ratio, height_ratio = utils.get_scale_ratios(action_event)
        
        x0 = window_event.left * width_ratio
        y0 = window_event.top * height_ratio
        x1 = x0 + window_event.width * width_ratio
        y1 = y0 + window_event.height * height_ratio
        box = (x0, y0, x1, y1)

        self._image = self._image.crop(box)
```

2023-05-31 02:44 UTC, 0dm commented on openadapt/temp_crop_test.py
> +    window_event = get_window_events(recording)[0]
use actionevent instead then, for ratios

2023-05-31 19:58 UTC, 0dm requested changes

2023-05-31 19:58 UTC, 0dm commented on openadapt/models.py
> +    def crop_active_window(self, action_event=None):
> **Warning**
Make action_event a required parameter

input (within visualize.py) :
```python
        im = action_event.screenshot
        im.crop_active_window() # => im.crop_active_window(action_event)
```
output:
```python
    window_event = action_event_to_use.window_event
AttributeError: 'InstrumentedList' object has no attribute 'window_event'
```

2023-06-02 14:37 UTC, abrichr commented on openadapt/temp_crop_test.py
> +    screenshot.image.show()
Please assert something about the output vs. expected

2023-06-13 14:56 UTC, merged