added filter for loguru
MLDSAI/OpenAdapt pull request #199
Opened 2023-05-29 20:20 UTC by 0dm

- resolves #180 using a filter for loguru

2023-05-29 20:28 UTC, 0dm commented
regarding this:

2023-06-02 14:11 UTC, abrichr requested changes

2023-06-02 15:11 UTC, 0dm commented on openadapt/utils.py
> +    return not any(data["message"].endswith(msg) for msg in messages_to_ignore)
sure, somehow didn't think of that

2023-06-02 15:13 UTC, 0dm commented
@abrichr should be good now

2023-06-02 19:53 UTC, abrichr commented on openadapt/utils.py
> +    messages_to_ignore = [
How about adding if `config.FILTER_WARNINGS:` here?

2023-06-13 13:13 UTC, closed without merging